using BitronCore.Api.Hubs;
using BitronCore.Application.Interfaces;
using BitronCore.Application.Services;
using BitronCore.Infrastructure.Mqtt;
using BitronCore.Infrastructure.Persistence;
using BitronCore.Infrastructure.Persistence.Repositories;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

// ── Persistencia ─────────────────────────────────────────────────────────────────────────────────────────────────
builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")));

builder.Services.AddScoped<IInspeccionRepository, InspeccionRepository>();

// ── Aplicación ──────────────────────────────────────────────────────────────────────────────────────────────────
builder.Services.AddScoped<InspeccionService>();

// ── MQTT ─────────────────────────────────────────────────────────────────────────────────────────────────────
builder.Services.Configure<MqttOptions>(builder.Configuration.GetSection(MqttOptions.SectionName));
builder.Services.AddHostedService<MqttBackgroundService>();

// ── SignalR ───────────────────────────────────────────────────────────────────────────────────────────────────
builder.Services.AddSignalR();
builder.Services.AddScoped<IInspeccionNotifier, SignalRInspeccionNotifier>();

// ── API ─────────────────────────────────────────────────────────────────────────────────────────────────────
builder.Services.AddControllers()
    .AddJsonOptions(opts =>
        opts.JsonSerializerOptions.PropertyNamingPolicy = System.Text.Json.JsonNamingPolicy.CamelCase);

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new() { Title = "Bitron Core API", Version = "v1" });
});

builder.Services.AddCors(options =>
    options.AddDefaultPolicy(policy =>
        policy.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod()));

var app = builder.Build();

// ── Esquema de base de datos ────────────────────────────────────────────────────────────────────────────────────
// EnsureCreatedAsync solo crea tablas en una DB nueva. Si el volumen de Postgres
// ya existía pero sin tablas, el SQL idempotente las crea de todas formas.
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    await db.Database.EnsureCreatedAsync();
    await db.Database.ExecuteSqlRawAsync("""
        CREATE TABLE IF NOT EXISTS inspecciones (
            "TransaccionId"    uuid                     NOT NULL,
            "DispositivoId"    character varying(100)   NOT NULL,
            "Linea"            character varying(50)    NOT NULL,
            "Timestamp"        timestamp with time zone NOT NULL,
            "ModeloDetectado"  character varying(20)    NOT NULL,
            "TiempoTotalMs"    integer                  NOT NULL,
            "VersionModeloKnn" character varying(20)    NOT NULL,
            "VeredictoGlobal"  character varying(2)     NOT NULL,
            "EvidenciaUrl"     character varying(500)   NULL,
            "CreadoEn"         timestamp with time zone NOT NULL DEFAULT now(),
            CONSTRAINT "PK_inspecciones" PRIMARY KEY ("TransaccionId")
        );

        CREATE TABLE IF NOT EXISTS analisis_roi (
            "Id"             integer                NOT NULL GENERATED BY DEFAULT AS IDENTITY,
            "InspeccionId"   uuid                   NOT NULL,
            "Zona"           character varying(100) NOT NULL,
            "Densidad"       double precision       NOT NULL,
            "BrilloPromedio" double precision       NOT NULL,
            "EsOk"           boolean                NOT NULL,
            CONSTRAINT "PK_analisis_roi" PRIMARY KEY ("Id"),
            CONSTRAINT "FK_analisis_roi_inspecciones_InspeccionId"
                FOREIGN KEY ("InspeccionId")
                REFERENCES inspecciones ("TransaccionId") ON DELETE CASCADE
        );

        CREATE INDEX IF NOT EXISTS "IX_inspecciones_Timestamp"
            ON inspecciones ("Timestamp");
        CREATE INDEX IF NOT EXISTS "IX_inspecciones_DispositivoId"
            ON inspecciones ("DispositivoId");
        CREATE INDEX IF NOT EXISTS "IX_inspecciones_Linea"
            ON inspecciones ("Linea");
        CREATE INDEX IF NOT EXISTS "IX_inspecciones_VeredictoGlobal"
            ON inspecciones ("VeredictoGlobal");
        CREATE INDEX IF NOT EXISTS "IX_inspecciones_Linea_Timestamp"
            ON inspecciones ("Linea", "Timestamp");
        CREATE INDEX IF NOT EXISTS "IX_analisis_roi_InspeccionId"
            ON analisis_roi ("InspeccionId");
        """);
}

// ── Middleware ────────────────────────────────────────────────────────────────────────────────────────────────────
app.UseSwagger();
app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "Bitron Core API v1"));

app.UseCors();
app.MapControllers();
app.MapHub<InspeccionHub>("/hubs/inspeccion");

app.Run();
